apiVersion: v1
kind: Secret
metadata:
  name: custody-secret
  namespace: custody
type: Opaque
stringData:
  # Helius API Key
  SOLANA_RPC_URL: "https://devnet.helius-rpc.com/?api-key=0168116a-7369-4cb6-a4f2-503a8d2aa832"

  # 외부 PostgreSQL Connection (host.docker.internal은 로컬 머신 접근)
  DATABASE_URL: "postgresql://custody:custody123@host.docker.internal:5432/custody"

  # 외부 RabbitMQ Connection
  RABBITMQ_URL: "amqp://coin:Coin1234!@49.50.138.148:5672"
