apiVersion: v1
kind: Service
metadata:
  name: custody-service
  namespace: custody
  labels:
    app: custody
spec:
  type: NodePort
  selector:
    app: custody
  ports:
  - protocol: TCP
    port: 3082
    targetPort: 3082
    nodePort: 30082  # 로컬에서 접근할 포트
